# See https://github.com/hvr/multi-ghc-travis for more information

language: c

sudo: false

matrix:
  include:
    - env: CABALVER=1.24 GHCVER=7.10.3
      addons: {apt: {packages: [cabal-install-1.24,ghc-7.10.3], sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=8.0.2
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2], sources: [hvr-ghc]}}
    - env: CABALVER=head GHCVER=head
      addons: {apt: {packages: [cabal-install-head,ghc-head],  sources: [hvr-ghc]}}

  allow_failures:
    - env: CABALVER=head GHCVER=head

# Dependencies required by grpc library.
addons:
  apt:
    packages:
      - build-essential
      - autoconf
      - libtool

before_install:
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 # Unfortunately it seems we have to fetch the full repository to be able to
 # clone it to create our workspace. We would be OK with a shallow repository
 # if we could make git to clone it.
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

install:
 - mkdir workspace
 - cp cabal.project.travis workspace/cabal.project
 - cd workspace
 - git clone --depth=1 .. grpc-haskell
 - git clone --depth=1 --recursive https://github.com/grpc/grpc grpc
 - cd grpc
 - make shared_c static_c interop_server -j
 - cd ..
 - cabal new-build --only-dependencies

script:
 - cabal new-build

notifications:
  email:
    - kolmodin@google.com
